---
- name: Install packages to disable Nvidia GPU
  become: true
  pacman:
    name:
      - linux-lts-headers
      - bbswitch-dkms

- name: Copy modprobe config to load & configure bbswitch (Turn off Nvidia GPU)
  become: true
  copy:
    src: "{{playbook_dir}}/etc/{{item}}"
    dest: "/etc/{{item}}"
    force: no
  loop:
    - modprobe.d/bbswitch.conf
    - modprobe.d/blacklisted.conf
    - modules-load.d/bbswitch.conf
  when: not linux_enable_gpu

- name: Remove modprobe config to load & configure bbswitch (Turn on Nvidia GPU)
  become: true
  file:
    path: "/etc/{{item}}"
    state: absent
  loop:
    - modprobe.d/bbswitch.conf
    - modprobe.d/blacklisted.conf
    - modules-load.d/bbswitch.conf
  when: linux_enable_gpu
