---
- name: Install NetworkManager (iwd version)
  yay:
    name:
      - networkmanager-iwd

- name: Install other NetworkManager related packages
  become: true
  pacman:
    name:
      - network-manager-applet
      - gnome-keyring

- name: Enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    enabled: yes
