#!/usr/bin/env bash

##################################################
# Timing commands. Copy the last line and add anywhere you want timing to be measured
##################################################
#curr_time() {
#    CURR_TIME=$(date +"%s%N" | cut -b1-13)
#}
#
#curr_time; BASHRC_TIME=$CURR_TIME
#curr_time; echo "A: $(($CURR_TIME-$BASHRC_TIME))"

# Need to be PC
alias person=man

source ~/.bash_aliases

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

##################################################
# Some Global Environment Variables (PATH, HIST*, etc)
##################################################

path_append() {
    if [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH="${PATH:+"$PATH:"}$1"
    fi
}

# Environment variables
export GOPATH="$HOME/go"
export TERM='rxvt-256color'
export EDITOR='vim'
path_append $HOME/node_modules/.bin:$HOME/.gem/ruby/2.5.0/bin:$GOPATH/bin

export HISTSIZE=100000
export HISTFILESIZE=100000
export HISTCONTROL=ignoreboth:erasedups

# &    => ignore duplicate commands
# [ ]* => ignore commands starting with a space
# exit => forget exit
export HISTIGNORE="&:[ ]*:exit:ls:clear:l:la:c:gla:g"
export HISTTIMEFORMAT='%F %T '

shopt -s histappend

export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source "/usr/bin/virtualenvwrapper_lazy.sh"

##################################################
# Bash Completion (Git, Atlas, etc)
##################################################

# Bash completion (including a bunch of cli tools like git, autorandr, etc)
bash_completion="/usr/share/bash-completion/bash_completion"
[[ -f $bash_completion ]] && . $bash_completion

# Add git completion to some custom git aliases
# Note: The Bash completion above already includes git completion for standard commands
git_completion="/usr/share/bash-completion/completions/git"
if [[ -f $git_completion ]]; then
    . $git_completion

    __git_complete g  __git_main
    __git_complete gu  _git_pull
    __git_complete gur _git_pull
    __git_complete gp  _git_push
    __git_complete ga  _git_add
    __git_complete gd  _git_diff
    __git_complete gda _git_diff
    __git_complete gs  _git_stash
    __git_complete gb  _git_branch
    __git_complete gba _git_branch
    __git_complete gc  _git_commit
    __git_complete gca _git_commit
    __git_complete gcl _git_clone
    __git_complete gco _git_checkout
    __git_complete gm  _git_merge
    __git_complete gff _git_merge
    __git_complete gl  _git_log
    __git_complete gla _git_log
    __git_complete gls _git_log
    __git_complete gll _git_log
    __git_complete gta _git_worktree
fi

# Add Atlas CLI completion in bash
[ $(command -v atlas) ] && source <(atlas --completion-script-bash)

##################################################
# Prompt (PROMPT_COMMAND, PS1)
##################################################

function color() {
    echo "\[$(tput setaf "${1}")\]"

    if [[ "$#" -eq 2 ]]; then
        echo "\[$(tput setab "${2}")\]"
    fi
}

function reset_color() {
    echo "\[$(tput setaf 7)\]"
}

function success_prompt() {
    # There's an opening parenthesis for some reason
    local last_status="${1//\(}"
    local success="^_^"
    local failure="0_o"
    if [[ "${last_status}" != "0" ]]; then
        echo "$(color 1)${failure}$(reset_color)"
    else
        echo "$(color 2)${success}$(reset_color)"
    fi
}

function bash_prompt_impl() {
    last_status=$(success_prompt $1)

    local login="$(color 4)\u$(reset_color)@$(color 6)\H$(reset_color)"
    local time="$(color 5)\t$(reset_color)"
    local directory="$(color 3)\w$(reset_color)"

    local virtualenv

    local sep="~"
    local lb="("
    local rb=")"

    if printenv VIRTUAL_ENV &>/dev/null; then
        virtualenv=$(printenv VIRTUAL_ENV | awk -F/ '{print $NF}')
        virtualenv="${sep}{${virtualenv}}"
    else
        virtualenv=""
    fi

    if git status &>/dev/null; then
        local rev=`git rev-parse --abbrev-ref HEAD 2>/dev/null`
        local gitbranch
        if [[ "${rev}" == "HEAD" ]]; then
            # "* (HEAD detached at origin/master)"
            gitbranch=$(git branch | egrep "^\*" | tail -c +4 | head -c -2)
        else
            # "* master"
            gitbranch=$(git branch | egrep "^\*" | tail -c +3)
        fi

        local status="$(git status -s)"
        local count_modified=$(echo "$status" | grep -E "^ [^\s]" | wc -l)
        local count_staged=$(echo "$status" | grep -E "^[^\s] " | wc -l)
        local count_untracked=$(echo "$status" | grep -E "^\?\?" | wc -l)

        if [[ ${count_untracked} != 0 ]]; then
            count_untracked=" $(color 3)...${count_untracked}$(reset_color)"
        else
            count_untracked=""
        fi

        if [[ ${count_modified} != 0 ]]; then
            count_modified=" $(color 1)+${count_modified}$(reset_color)"
        else
            count_modified=""
        fi

        if [[ ${count_staged} != 0 ]]; then
            count_staged=" $(color 2)●${count_staged}$(reset_color)"
        else
            count_staged=""
        fi

        # M == Modified and Unstaged ●
        # D == Deleted  -
        # R == Renamed  R
        # C == Copied   C
        # U == Updated but Unmerged
        # A == Added
        # "??" == Untracked
        local gitprompt="${sep}${lb}${gitbranch}${count_staged}${count_modified}${count_untracked}${rb}"
    fi

    # Set the terminal title to current working directory
    # https://askubuntu.com/questions/745529/what-does-this-bash-escape-sequence-mean
    echo -ne "\e]0;\w\007"

    echo ""
    echo -n "${lb}${last_status}${rb}"
    echo -n "${sep}"
    echo -n "${lb}${time}${rb}"

    # TODO display login only if different from normal
    #echo -n "${sep}"
    #echo -n "${lb}${login}${rb}"

    echo -n "${virtualenv}"
    echo -n "${sep}"
    echo -n "${lb}${directory}${rb}"
    echo -n "${gitprompt}"
    echo ""
    echo "$ "
}

function bash_prompt() {
    last_status=$?

    # Note: If history is in $PS1, then weird things happen
    history -a
    history -c
    history -r

    PS1=`bash_prompt_impl $last_status`
}

prompt_prepend() {
    if [[ "$PROMPT_COMMAND" != *"$1"* ]]; then
        PROMPT_COMMAND="$1 ${PROMPT_COMMAND:+"$PROMPT_COMMAND ;"}"
    fi
}

# Append to PROMPT_COMMAND because of autojump: https://github.com/wting/autojump
prompt_prepend bash_prompt
export PROMPT_COMMAND

source "/etc/profile.d/autojump.bash"

##################################################
# Colors (base16)
##################################################

# base16-shell (https://github.com/chriskempson/base16-shell)
# Base16 Shell template by Chris Kempson (http://chriskempson.com)
# Tomorrow Night scheme by Chris Kempson (http://chriskempson.com)
function base16 () {
    color00="1d/1f/21" # Base 00 - Black
    color01="cc/66/66" # Base 08 - Red
    color02="b5/bd/68" # Base 0B - Green
    color03="f0/c6/74" # Base 0A - Yellow
    color04="81/a2/be" # Base 0D - Blue
    color05="b2/94/bb" # Base 0E - Magenta
    color06="8a/be/b7" # Base 0C - Cyan
    color07="c5/c8/c6" # Base 05 - White
    color08="96/98/96" # Base 03 - Bright Black
    color09=$color01 # Base 08 - Bright Red
    color10=$color02 # Base 0B - Bright Green
    color11=$color03 # Base 0A - Bright Yellow
    color12=$color04 # Base 0D - Bright Blue
    color13=$color05 # Base 0E - Bright Magenta
    color14=$color06 # Base 0C - Bright Cyan
    color15="ff/ff/ff" # Base 07 - Bright White
    color16="de/93/5f" # Base 09
    color17="a3/68/5a" # Base 0F
    color18="28/2a/2e" # Base 01
    color19="37/3b/41" # Base 02
    color20="b4/b7/b4" # Base 04
    color21="e0/e0/e0" # Base 06
    color_foreground="c5/c8/c6" # Base 05
    color_background="1d/1f/21" # Base 00
    color_cursor="c5/c8/c6" # Base 05

    if [ -n "$TMUX" ]; then
        # Tell tmux to pass the escape sequences through
        # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
        printf_template="\033Ptmux;\033\033]4;%d;rgb:%s\007\033\\"
        printf_template_var="\033Ptmux;\033\033]%d;rgb:%s\007\033\\"
        printf_template_custom="\033Ptmux;\033\033]%s%s\007\033\\"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf_template="\033P\033]4;%d;rgb:%s\007\033\\"
        printf_template_var="\033P\033]%d;rgb:%s\007\033\\"
        printf_template_custom="\033P\033]%s%s\007\033\\"
    else
        printf_template="\033]4;%d;rgb:%s\033\\"
        printf_template_var="\033]%d;rgb:%s\033\\"
        printf_template_custom="\033]%s%s\033\\"
    fi

    # We only require the 256-bit colors, colors 0-15 are handled correctly by .Xresources
    printf $printf_template 16 $color16
    printf $printf_template 17 $color17
    printf $printf_template 18 $color18
    printf $printf_template 19 $color19
    printf $printf_template 20 $color20
    printf $printf_template 21 $color21

    # clean up
    unset printf_template
    unset printf_template_var
    unset color00
    unset color01
    unset color02
    unset color03
    unset color04
    unset color05
    unset color06
    unset color07
    unset color08
    unset color09
    unset color10
    unset color11
    unset color12
    unset color13
    unset color14
    unset color15
    unset color16
    unset color17
    unset color18
    unset color19
    unset color20
    unset color21
    unset color_foreground
    unset color_background
    unset color_cursor
}

base16

##################################################
# SSH Keys + Agent
##################################################

SSH_ENV="$HOME/.ssh/agent-environment"

function start_agent {
    /usr/bin/ssh-agent > "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    # TODO: See if I should use this
    #/usr/bin/ssh-add $HOME/.ssh/atlassian
}

if [[ -f "${SSH_ENV}" ]]; then
    . "${SSH_ENV}" > /dev/null
    ps -ef | grep ${SSH_AGENT_PID} | grep -e "ssh-agent$" > /dev/null || {
        start_agent
    }
else
    start_agent
fi
