#!/bin/bash

# Sourced by LightDM (/etc/lightdm/Xsession): https://wiki.archlinux.org/title/xprofile

# Setup environment so user scripts can get used
export PATH=$PATH:$HOME/bin

# Set how the cursor looks
xsetroot -cursor_name left_ptr

# Set key repeat offset & rate to be quicker
# TODO: Need to run this whenever a new keyboard connects I think
xset r rate 300 30

# Programs are started in ~/.xsession
