#!/bin/bash

# Sourced by LightDM (/etc/lightdm/Xsession): https://wiki.archlinux.org/title/xprofile

# Start tray programs
blueman-applet &
GDK_SCALE=1 nm-applet &
redshift-gtk -l -33.86482:151.20773 &

# Start lock-related programs
light-locker --lock-after-screensaver 60 --no-lock-on-lid &
screenlock &

# Start other programs
autorandr --change
urxvtd --quiet --opendisplay --fork &

# X-specific setup/config are in ~/.xprofile
