---
- name: Install Awesome
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - awesome
  become: true

- name: Create .config/awesome
  file:
    path: "~/.config/awesome"
    state: directory

- name: Link .config/awesome/rc.lua
  file:
    src: "{{playbook_dir}}/home/config/awesome/rc.lua"
    dest: "~/.config/awesome/rc.lua"
    state: link

- name: Link .config/awesome/themes
  file:
    src: "{{playbook_dir}}/home/config/awesome/themes"
    dest: "~/.config/awesome/themes"
    state: link

- name: Clone repos
  git:
    repo: "{{item.url}}"
    dest: "{{playbook_dir}}/src/{{item.dest}}"
    version: master
  loop:
    - url: "https://github.com/NuckChorris/assault.git"
      dest: "github.com/NuckChorris/assault"
    - url: "https://github.com/scottgreenup/lain.git"
      dest: "github.com/scottgreenup/lain"
    - url: "https://github.com/majutsushi/urxvt-font-size.git"
      dest: "github.com/majutsushi/urxvt-font-size"
    - url: "https://github.com/vicious-widgets/vicious.git"
      dest: "github.com/vicious-widgets/vicious"

# TODO: Move urxvt stuff to another task file
- name: Create .urxvt/ext
  file:
    path: "~/.urxvt/ext"
    state: directory

- name: Link repo contents for urxvt
  file:
    src: "{{playbook_dir}}/src/{{item.src}}"
    dest: "~/.urxvt/ext/{{item.dest}}"
    state: link
  loop:
    - src: "github.com/majutsushi/urxvt-font-size/font-size"
      dest: "font-size"

- name: Link repo contents for awesome
  file:
    src: "{{playbook_dir}}/src/{{item.src}}"
    dest: "~/.config/awesome/{{item.dest}}"
    state: link
  loop:
    - src: "github.com/NuckChorris/assault/awesomewm/assault.lua"
      dest: "assault.lua"
    - src: "github.com/scottgreenup/lain"
      dest: "lain"
    - src: "github.com/vicious-widgets/vicious/"
      dest: "vicious"
