---
- name: Install Awesome
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - awesome

- name: Link config for awesome
  file:
    src: "{{playbook_dir}}/home/config/awesome"
    dest: "~/.config/awesome"
    state: link

- name: Define awesome package repos
  set_fact:
    packages:
      - name: "github.com/NuckChorris/assault"
        src: "/awesomewm/assault.lua"
        dest: "assault.lua"
      - name: "github.com/scottgreenup/lain"
        src: ""
        dest: "lain"
      - name: "github.com/vicious-widgets/vicious"
        src: ""
        dest: "vicious"

- name: Clone awesome package repos
  git:
    repo: "https://{{item.name}}.git"
    dest: "{{playbook_dir}}/src/{{item.name}}"
    version: master
  loop: "{{packages}}"

- name: Link repo contents for awesome
  file:
    src: "{{playbook_dir}}/src/{{item.name}}{{item.src}}"
    dest: "~/.config/awesome/{{item.dest}}"
    state: link
  loop: "{{packages}}"
