---
- name: Install Flameshot
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - flameshot

- name: Link config for flameshot
  file:
    src: "{{playbook_dir}}/home/config/Dharkael"
    dest: "~/.config/Dharkael"
    state: link
