---
- name: Install Flameshot
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - flameshot

- name: Link config for flameshot
  file:
    src: "{{playbook_dir}}/home/config/Dharkael"
    dest: "~/.config/Dharkael"
    state: link
