---
- name: Install i3
  become: true
  pacman:
    name:
      - i3-gaps
      - i3status

- name: Link config for i3
  file:
    src: "{{playbook_dir}}/home/config/{{item}}"
    dest: "~/.config/{{item}}"
    state: link
  loop:
    - "i3"
    - "i3status"
