---
- name: Install i3
  become: true
  pacman:
    name:
      - i3-gaps
      - i3status

- name: Link config for i3
  file:
    src: "{{playbook_dir}}/home/config/{{item}}"
    dest: "~/.config/{{item}}"
    state: link
  loop:
    - "i3"
    - "i3status"

- name: Link bluetooth_battery timer for i3status
  become: true
  file:
    src: "{{playbook_dir}}/etc/systemd/system/{{item}}"
    dest: "/etc/systemd/system/{{item}}"
    state: link
  loop:
    - "bluetooth_battery.service"
    - "bluetooth_battery.timer"

- name: Enable bluetooth_battery.timer
  become: true
  systemd:
    name: bluetooth_battery.timer
    enabled: yes
    state: started
    daemon_reload: yes
