--
- name: Install Kitty
  become: true
  pacman:
    name:
      - kitty

- name: Link config for kitty
  file:
    src: "{{playbook_dir}}/home/config/{{item}}"
    dest: "~/.config/{{item}}"
    state: link
  loop:
    - "kitty"
