---
- name: Install Lightdm
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - lightdm
      - lightdm-gtk-greeter

# TODO: Decide whether I want lightdm-gtk-greeter or lightdm-webkit2-greeter
# TODO: Copy the file, or use lineinfile task, instead of copying
#- name: Copy /etc/lightdm/lightdm.conf
#  become: true
#  copy:
#    src: "{{playbook_dir}}/etc/lightdm/lightdm.conf"
#    dest: "/etc/lightdm/lightdm.conf"

- name: Enable LightDM
  become: true
  systemd:
    name: lightdm
    enabled: yes
