---
- name: Install LightDM
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings

# TODO: Decide whether I want lightdm-gtk-greeter or lightdm-webkit2-greeter
# If webkit2, then copy lightdm.conf

- name: Copy LightDM config
  become: true
  copy:
    src: "{{playbook_dir}}/etc/lightdm/lightdm-gtk-greeter.conf"
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"

- name: Copy LightDM background
  become: true
  copy:
    src: "{{playbook_dir}}/etc/lightdm/Arch-logo-side-navy-background.png"
    dest: "/etc/lightdm/lightdm-background.png"

- name: Enable LightDM
  become: true
  systemd:
    name: lightdm
    enabled: yes
