---
- name: Install LightDM
  become: true
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings
      - light-locker

- name: Copy LightDM config
  become: true
  copy:
    src: "{{playbook_dir}}/etc/lightdm/lightdm-gtk-greeter.conf"
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"

- name: Copy LightDM background
  become: true
  copy:
    src: "{{playbook_dir}}/etc/lightdm/Arch-logo-neon-japanese-background.png"
    dest: "/etc/lightdm/lightdm-background.png"

- name: Link Desktop Manager config
  file:
    src: "{{playbook_dir}}/home/dmrc"
    dest: "~/.dmrc"
    state: link

- name: Enable LightDM
  become: true
  systemd:
    name: lightdm
    enabled: yes
