---
- name: Create .config
  file:
    path: "~/.config"
    state: directory

- name: Link home directories
  file:
    src: "{{playbook_dir}}/{{item.src}}"
    dest: "~/{{item.dest}}"
    state: link
    force: yes
  loop:
    - src: "home/autorandr"
      dest: ".autorandr"
    - src: "home/bin"
      dest: "bin"

- name: Link dotfiles
  file:
    src: "{{playbook_dir}}/{{item.src}}"
    dest: "~/{{item.dest}}"
    state: link
    force: yes
  loop:
    - src: "home/xprofile"
      dest: ".xprofile"
    - src: "home/bashrc"
      dest: ".bashrc"
    - src: "home/bash_aliases"
      dest: ".bash_aliases"
    - src: "home/Xresources"
      dest: ".Xresources"
    - src: "home/inputrc"
      dest: ".inputrc"

- include: awesome.yaml
- include: lightdm.yaml
- include: vim.yaml
- include: urxvt.yaml
