---
- name: Create .config
  file:
    path: "~/.config"
    state: directory

- name: Link home directories
  file:
    src: "{{playbook_dir}}/{{item.src}}"
    dest: "~/{{item.dest}}"
    state: link
  loop:
    - src: "home/config/autorandr"
      dest: ".config/autorandr"
    - src: "home/bin"
      dest: "bin"

- name: Link dotfiles
  file:
    src: "{{playbook_dir}}/{{item.src}}"
    dest: "~/{{item.dest}}"
    state: link
  loop:
    - src: "home/xprofile"
      dest: ".xprofile"
    - src: "home/xsession"
      dest: ".xsession"
    - src: "home/bashrc"
      dest: ".bashrc"
    - src: "home/bash_aliases"
      dest: ".bash_aliases"
    - src: "home/Xresources"
      dest: ".Xresources"
    - src: "home/inputrc"
      dest: ".inputrc"
    - src: "home/gitconfig"
      dest: ".gitconfig"
    - src: "home/gitignore"
      dest: ".gitignore"

- name: Clone terminal color repo
  when: perform_git_update
  git:
    repo: "{{item.url}}"
    dest: "{{playbook_dir}}/src/{{item.dest}}"
    version: master
  loop:
    - url: "https://github.com/chriskempson/base16-shell.git"
      dest: "github.com/chriskempson/base16-shell"
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Link terminal color package
  file:
    src: "{{playbook_dir}}/src/{{item.src}}"
    dest: "~/.config/{{item.dest}}"
    state: link
  loop:
    - src: "github.com/chriskempson/base16-shell"
      dest: "base16-shell"

- import_tasks: awesome.yaml
- import_tasks: flameshot.yaml
- import_tasks: i3.yaml
- import_tasks: lightdm.yaml
- import_tasks: notifications.yaml
- import_tasks: power-management.yaml
- import_tasks: redshift.yaml
- import_tasks: vim.yaml
- import_tasks: urxvt.yaml
- import_tasks: xorg.yaml
