---
- name: Create .config
  file:
    path: "~/.config"
    state: directory

- name: Link home directories
  file:
    src: "{{playbook_dir}}/{{item.src}}"
    dest: "~/{{item.dest}}"
    state: link
    force: yes
  loop:
    - src: "home/autorandr"
      dest: ".autorandr"
    - src: "home/bin"
      dest: "bin"

- name: Link dotfiles
  file:
    src: "{{playbook_dir}}/{{item.src}}"
    dest: "~/{{item.dest}}"
    state: link
    force: yes
  loop:
    - src: "home/xprofile"
      dest: ".xprofile"
    - src: "home/bashrc"
      dest: ".bashrc"
    - src: "home/bash_aliases"
      dest: ".bash_aliases"
    - src: "home/Xresources"
      dest: ".Xresources"
    - src: "home/inputrc"
      dest: ".inputrc"
    - src: "home/gitconfig"
      dest: ".gitconfig"
    - src: "home/gitignore"
      dest: ".gitignore"

- name: Clone terminal color repo
  git:
    repo: "{{item.url}}"
    dest: "{{playbook_dir}}/src/{{item.dest}}"
    version: master
  loop:
    - url: "https://github.com/chriskempson/base16-shell.git"
      dest: "github.com/chriskempson/base16-shell"

- name: Link terminal color package
  file:
    src: "{{playbook_dir}}/src/{{item.src}}"
    dest: "~/.config/{{item.dest}}"
    state: link
  loop:
    - src: "github.com/chriskempson/base16-shell"
      dest: "base16-shell"

- include: awesome.yaml
- include: flameshot.yaml
- include: lightdm.yaml
- include: vim.yaml
- include: urxvt.yaml
- include: xorg.yaml
