---
- name: Install power management packages
  become: true
  pacman:
    name:
      - acpi
      - acpi_call
      - acpi_call-lts
      - powertop
      - tlp

- name: Copy TLP config
  become: true
  copy:
    src: "{{playbook_dir}}/etc/tlp.conf"
    dest: "/etc/tlp.conf"
    force: no

- name: Append manual step - Configure TLP config
  set_fact:
    manual_steps: "{{ manual_steps + [ 'TLP - Double check all the TLP config is set to the right values for a new installation' ] }}"

- name: Enable TLP
  become: true
  systemd:
    name: tlp
    enabled: yes
