---
- name: Install power management packages
  become: true
  pacman:
    name:
      - acpi
      - acpi_call
      - acpi_call-lts
      - powertop
      - tlp

# TODO: Save the /etc/tlp.conf file

- name: Enable TLP
  become: true
  systemd:
    name: tlp
    enabled: yes
