---
- name: Install Urxvt
  become: true
  pacman:
    name:
      - rxvt-unicode
      - urxvt-perls # Needed for urxvt to find the 'clipboard' perl extension

- name: Create .urxvt/ext
  file:
    path: "~/.urxvt/ext"
    state: directory

- name: Clone urxvt extension repos
  when: perform_git_update
  git:
    repo: "{{item.url}}"
    dest: "{{playbook_dir}}/src/{{item.dest}}"
    version: master
  loop:
    - url: "https://github.com/majutsushi/urxvt-font-size.git"
      dest: "github.com/majutsushi/urxvt-font-size"
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Link repo contents for urxvt
  file:
    src: "{{playbook_dir}}/src/{{item.src}}"
    dest: "~/.urxvt/ext/{{item.dest}}"
    state: link
  loop:
    - src: "github.com/majutsushi/urxvt-font-size/font-size"
      dest: "font-size"
