---
# TODO: Install urxvt maybe?

- name: Create .urxvt/ext
  file:
    path: "~/.urxvt/ext"
    state: directory

- name: Clone urxvt extension repos
  git:
    repo: "{{item.url}}"
    dest: "{{playbook_dir}}/src/{{item.dest}}"
    version: master
  loop:
    - url: "https://github.com/majutsushi/urxvt-font-size.git"
      dest: "github.com/majutsushi/urxvt-font-size"

- name: Link repo contents for urxvt
  file:
    src: "{{playbook_dir}}/src/{{item.src}}"
    dest: "~/.urxvt/ext/{{item.dest}}"
    state: link
  loop:
    - src: "github.com/majutsushi/urxvt-font-size/font-size"
      dest: "font-size"
