---
- name: Install Vim
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - vim

- name: Link .vimrc
  file:
    src: "{{playbook_dir}}/home/vimrc"
    dest: "~/.vimrc"
    state: link
