---
- name: Install Vim
  become: true
  pacman:
    name:
      - vim

- name: Link .vimrc
  file:
    src: "{{playbook_dir}}/home/vimrc"
    dest: "~/.vimrc"
    state: link

- name: Link .vim
  file:
    src: "{{playbook_dir}}/home/vim"
    dest: "~/.vim"
    state: link

- name: Create vim packages folder
  file:
    path: "~/.vim/pack/packages/start"
    state: directory

- name: Create vim colors folder
  file:
    path: "~/.vim/colors"
    state: directory

- name: Create vim tmp folder
  file:
    path: "~/.vim/tmp"
    state: directory

# TODO: Try more packages until all the comments are gone!
- name: Define vim package names
  set_fact:
    vim_packages:
      #- name: "github.com/scrooloose/nerdtree"
      - name: "github.com/ntpeters/vim-better-whitespace"
      #- name: "github.com/pangloss/vim-javascript"
      #- name: "github.com/tpope/vim-fugitive"
      #- name: "github.com/tomlion/vim-solidity"
      #- name: "github.com/nvie/vim-flake8"
      #- name: "github.com/ekalinin/Dockerfile"
      #- name: "github.com/junegunn/fzf"
      #- name: "github.com/airblade/vim-gitgutter"
    vim_colour_schemes:
      - name: "github.com/chriskempson/base16-vim"
        src: "colors/base16-tomorrow.vim"

- name: Clone vim package repos
  when: perform_git_update
  git:
    repo: "https://{{item.name}}.git"
    dest: "{{playbook_dir}}/src/{{item.name}}"
    version: master
    force: yes
  loop: "{{vim_packages + vim_colour_schemes}}"
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Apply some small improvements to vim colors
  lineinfile:
    path: "{{playbook_dir}}/src/github.com/chriskempson/base16-vim/colors/base16-tomorrow.vim"
    regexp: "{{item.regex}}"
    line: "{{item.result}}"
  loop:
    - regex: ".*SpellBad.*"
      result: 'call <sid>hi("SpellBad",     "", "", "", s:cterm00, "undercurl", s:gui08)'
    - regex: ".*SpellLocal.*"
      result: 'call <sid>hi("SpellLocal",   "", "", "", s:cterm00, "undercurl", s:gui0C)'
    - regex: ".*SpellCap.*"
      result: 'call <sid>hi("SpellCap",     "", "", "", s:cterm00, "undercurl", s:gui0D)'
    - regex: ".*SpellRare.*"
      result: 'call <sid>hi("SpellRare",    "", "", "", s:cterm00, "undercurl", s:gui0E)'

- name: Link vim packages
  file:
    src: "{{playbook_dir}}/src/{{item.name}}"
    dest: "~/.vim/pack/packages/start/{{item.name.rsplit('/', 1)[1]}}"
    state: link
  loop: "{{vim_packages}}"

- name: Link vim colors
  file:
    src: "{{playbook_dir}}/src/{{item.name}}/{{item.src}}"
    dest: "~/.vim/colors/{{item.src.rsplit('/', 1)[1]}}"
    state: link
  loop: "{{vim_colour_schemes}}"
