---
- name: Install Vim
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - vim

- name: Link .vimrc
  file:
    src: "{{playbook_dir}}/home/vimrc"
    dest: "~/.vimrc"
    state: link

- name: Link .vim
  file:
    src: "{{playbook_dir}}/home/vim"
    dest: "~/.vim"
    state: link

- name: Create vim packages folder
  file:
    path: "~/.vim/pack/packages/start"
    state: directory

# TODO: Try more packages until all the comments are gone!
- name: Define vim package names
  set_fact:
    packages:
      #- name: "github.com/scrooloose/nerdtree"
      - name: "github.com/ntpeters/vim-better-whitespace"
      #- name: "github.com/pangloss/vim-javascript"
      #- name: "github.com/tpope/vim-fugitive"
      #- name: "github.com/tomlion/vim-solidity"
      #- name: "github.com/nvie/vim-flake8"
      #- name: "github.com/ekalinin/Dockerfile"
      #- name: "github.com/junegunn/fzf"
      #- name: "github.com/airblade/vim-gitgutter"
    colour_schemes:
      - name: "github.com/chriskempson/base16-vim"

- name: Clone vim package repos
  git:
    repo: "https://{{item.name}}.git"
    dest: "{{playbook_dir}}/src/{{item.name}}"
    version: master
  loop: "{{packages + colour_schemes}}"

- name: Link vim packages
  file:
    src: "{{playbook_dir}}/src/{{item.name}}"
    dest: "~/.vim/pack/packages/start/{{item.name.rsplit('/', 1)[1]}}"
    state: link
  loop: "{{packages}}"

- name: Link vim colors
  file:
    src: "{{playbook_dir}}/src/{{item.src}}"
    dest: "~/.vim/colors/{{item.dest}}"
    state: link
  loop:
    - src: "{{colour_schemes[0]['name']}}/colors/base16-tomorrow.vim"
      dest: "base16-tomorrow.vim"
