---
- name: Install Xorg, video drivers, and other utilities
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - i3lock
      - mesa
      - xautolock
      - xclip
      - xf86-video-intel
      - xf86-input-libinput
      - xorg-server
      - xorg-xbacklight
      - xorg-xinput
      - xorg-xrdb

- name: Link touchpad config that Xorg reads
  become: true
  file:
    src: "{{playbook_dir}}/etc/X11/xorg.conf.d/30-touchpad.conf"
    dest: "/etc/X11/xorg.conf.d/30-touchpad.conf"
    state: link
