---
- name: Install Xorg, video drivers, and other utilities
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - i3lock
      - mesa
      - xautolock
      - xclip
      - xf86-video-intel
      - xf86-input-libinput
      - xorg-server
      - xorg-server-xephyr
      - xorg-xbacklight
      - xorg-xinput
      - xorg-xrdb
      - xorg-xsetroot

- name: Copy touchpad config that Xorg reads (link doesn't work when $HOME isn't open yet)
  become: true
  copy:
    src: "{{playbook_dir}}/etc/X11/xorg.conf.d/{{item}}"
    dest: "/etc/X11/xorg.conf.d/{{item}}"
    force: no
  loop:
    - 30-touchpad.conf
    - 30-mouse.conf
