start-at-login = true

# Most i3-like configs have this "normalization" feature turned off,
# but I haven't needed to disable it yet for my usage. (TODO: Testing)
# Typically needed to use the "split" command.
#enable-normalization-flatten-containers = false

# Default to a fullscreen-like mode
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'

# Remove padding from accordion layout
accordion-padding = 0

# Mouse follows focus when focused monitor or window changes (TODO: Testing)
#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Disable the MasOS "hide application" feature that is usually triggered via cmd+h
automatically-unhide-macos-hidden-apps = false

[mode.main.binding]
  alt-1 = 'workspace 1'
  alt-2 = 'workspace 2'
  alt-3 = 'workspace 3'
  alt-4 = 'workspace 4'
  alt-5 = 'workspace 5'
  alt-6 = 'workspace 6'
  alt-7 = 'workspace 7'
  alt-8 = 'workspace 8'
  alt-9 = 'workspace 9'

  alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
  alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
  alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
  alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
  alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
  alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
  alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
  alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
  alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

  # TODO: Testing without a "fullscreen" mode, because a borderless accordion mode is equivalent,
  # and allows cycling between "fullscreen" windows in the same workspace.
  #alt-f = 'fullscreen'

  # Layouts to toggle between
  alt-shift-space = 'layout v_accordion h_tiles'

  # Move a workspace to another monitor
  alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

  # Using dfs next/prev to move "up/down" between all windows on a workspace,
  # regardless of whether they are to the right/left/above/below.
  alt-j = 'focus --boundaries-action wrap-around-the-workspace dfs-next'
  alt-k = 'focus --boundaries-action wrap-around-the-workspace dfs-prev'

  # TODO: Testing commands to switch/move windows within a workspace
  alt-shift-j = 'move left'
  alt-shift-k = 'move right'

  alt-shift-h = 'resize smart -50'
  alt-shift-l = 'resize smart +50'
