---
- name: Get the homebrew/cask-versions
  homebrew_tap:
    name:
      - homebrew/cask-versions
  when: mac_os

- name: Install Web Browsers
  homebrew_cask:
    name:
      - firefox-developer-edition
  when: mac_os

- name: Install Web Browsers
  become: true
  pacman:
    name:
      - firefox
  when: linux

- name: Install Web Browsers - yay
  yay:
    name:
      - google-chrome
  when: linux
