---
- name: Create code directory
  file:
    path: "~/code"
    state: directory

# TODO: Figure out what to do when there's local modifications to the script (e.g: credentials)
#- name: Clone internet_usage repo
#  when: perform_git_update
#  git:
#    repo: "git@bitbucket-personal.org:hbotp/internet-usage.git"
#    dest: "~/code/internet-usage"
#    version: master
#  register: git_result
#  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

# TODO: Figure out how to get credentials into the script

- name: Link get_internet_usage script
  become: true
  file:
    src: "{{playbook_dir}}/../code/internet-usage/{{item}}"
    dest: "/usr/local/bin/{{item}}"
    state: link
  loop:
    - "get_internet_usage"

# Systemd needs the files to be accessible from outside any home directories
- name: Copy get_internet_usage service and timer
  become: true
  copy:
    src: "{{playbook_dir}}/../code/internet-usage/{{item}}"
    dest: "/etc/systemd/system/{{item}}"
    force: no
  loop:
    - "get_internet_usage.service"
    - "get_internet_usage.timer"

- name: Enable get_internet_usage.timer
  become: true
  systemd:
    name: get_internet_usage.timer
    enabled: yes
    state: started
    daemon_reload: yes
