---
- name: Install kernel-modules-hook
  become: true
  pacman:
    name:
      - kernel-modules-hook
  register: kernel_modules_hook_installation

- name: Post-install commands for kernel-modules-hook
  when: kernel_modules_hook_installation is changed
  systemd:
    name: linux-modules-cleanup
    enabled: yes
    daemon_reload: yes
