---
# TODO: Migrate all of these into proper task files in the relevant roles. E.g:
# * fonts
# * slack
# * cli-utils
# * git
# * yubikey
# * signal
# * python
# * postman
# * spotify
# * zoom

- name: Install common fonts
  become: true
  pacman:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-anonymous-pro
      - ttf-dejavu
      - ttf-liberation

- name: Install CLI utilities
  become: true
  pacman:
    name:
      - git
      - htop
      - jq
      - keychain
      - sed
      - the_silver_searcher
      - tree
      - unzip
      # TODO: Separate into other roles/tasks
      - arandr
      - bind
      - feh
      - gping
      - gnu-netcat
      - ipcalc
      - openldap
      - pacman-contrib
      - signal-desktop
      - traceroute
      - vlc
      - yubikey-manager
      - yubikey-manager-qt

- name: Install some AUR packages - yay
  yay:
    name:
      - autojump
      - postman-bin
      - slack-desktop
      - spotify
      - zoom

- name: Install Python
  become: true
  pacman:
    name:
      - python
      - python-pip
      - python-tox
      - python-virtualenv
      - python-virtualenvwrapper
