---
# TODO: Can I group some of these task lists?
- import_tasks: browser.yaml
- import_tasks: docker.yaml
- import_tasks: flameshot.yaml
- import_tasks: git.yaml
- include_tasks: grub.yaml
  when: linux
- include_tasks: i3.yaml
  when: linux
- import_tasks: ide.yaml
- include_tasks: karabiner.yaml
  when: mac_os
- import_tasks: kitty.yaml
- include_tasks: lightdm.yaml
  when: linux
- import_tasks: vim.yaml
- import_tasks: zsh.yaml


# TODO: Move these tasks into an appropriate role
# old-common
# └── tasks
#     ├── backlight.yaml            # io
#     ├── bluetooth.yaml            # io
#     ├── gpu.yaml                  # io
#     ├── internet.yaml             # io
#     ├── internet_usage.yaml       # applications
#     ├── kernel-modules-hook.yaml  # applications?
#     ├── main.yaml                 # todo: split
#     ├── paprika.yaml              # applications
#     ├── sound.yaml                # io
#     ├── ssd.yaml                  # io
#     ├── systemd.yaml              # applications?
#     └── udev.yaml                 # io
# old-desktop-environment
# └── tasks
#     ├── main.yaml                 # todo: split
#     ├── notifications.yaml        # applications
#     ├── power-management.yaml     # io
#     ├── redshift.yaml             # applications
#     ├── rofi.yaml                 # applications
#     └── xorg.yaml                 # applications
