---
# A role that contains tasks related to applications installed on a system

# Some basic setup tasks
- name: Create .config
  file:
    path: "~/.config"
    state: directory

- name: Link home directories
  file:
    src: "{{playbook_dir}}/home/{{item}}"
    dest: "~/{{item}}"
    state: link
  loop:
    - bin

- include_tasks: autorandr.yaml
  when: linux
# TODO: Cleanup bash config if I'm not going to use it anymore
#- include_tasks: bash.yaml
#  when: linux
- import_tasks: browser.yaml
- import_tasks: docker.yaml
- import_tasks: flameshot.yaml
- import_tasks: git.yaml
- include_tasks: grub.yaml
  when: linux
- include_tasks: i3.yaml
  when: linux
- import_tasks: ide.yaml
- include_tasks: karabiner.yaml
  when: mac_os
- import_tasks: kitty.yaml
- include_tasks: lightdm.yaml
  when: linux
- import_tasks: vim.yaml
- import_tasks: zsh.yaml

# TODO: Expand this to Mac
- include_tasks: internet_usage.yaml
  when: linux
- include_tasks: kernel-modules-hook.yaml
  when: linux
# TODO: Maybe expand this to Mac?
- include_tasks: paprika.yaml
  when: linux
- include_tasks: systemd.yaml
  when: linux
# TODO: Maybe expand this to Mac?
- include_tasks: notifications.yaml
  when: linux
# TODO: Is there anything that would be tweaked on a Mac here?
- include_tasks: redshift.yaml
  when: linux
- include_tasks: rofi.yaml
  when: linux
- include_tasks: xorg.yaml
  when: linux
- include_tasks: .yaml
  when: linux

# TODO: Move these tasks into an appropriate role
# old-common
# └── tasks
#     ├── main.yaml                 # todo: split
# old-desktop-environment
# └── tasks
#     ├── main.yaml                 # todo: split
