---
- name: Make some systemd config directories
  file:
    path: "/etc/systemd/{{item}}"
    state: directory
  loop:
    - "logind.conf.d"
    - "sleep.conf.d"

# Copy instead of link, because systemd needs to see them before the user logs in
- name: Copy some systemd config files
  become: true
  copy:
    src: "{{playbook_dir}}/etc/systemd/{{item}}"
    dest: "/etc/systemd/{{item}}"
    force: no
  loop:
    - "logind.conf.d/logind.conf"
    - "sleep.conf.d/sleep.conf"
