---
- name: Install Xorg, video drivers, and other utilities
  become: true
  pacman:
    name:
      - mesa
      - xclip
      - xf86-input-libinput
      - xorg-server
      - xorg-server-xephyr
      - xorg-xinput
      - xorg-xrdb
      - xorg-xsetroot

- name: Install xidlehook & xautocfg
  become: true
  yay:
    name:
      - xidlehook
      - xautocfg

- name: Copy touchpad config that Xorg reads (symlink doesn't work when $HOME isn't open yet)
  become: true
  copy:
    src: "{{playbook_dir}}/etc/X11/xorg.conf.d/{{item}}"
    dest: "/etc/X11/xorg.conf.d/{{item}}"
    force: no
  loop:
    - 30-touchpad.conf
    - 30-mouse.conf

- name: Link xautocfg config file (for keyboard settings)
  file:
    src: "{{playbook_dir}}/home/{{item}}"
    dest: "~/.{{item}}"
    state: link
  loop:
    - config/xautocfg.cfg
    - xprofile
    - xsession
    - Xresources
    - inputrc
