---
- include_tasks: brew.yaml
  when: ansible_facts['os_family'] == 'Darwin'

- include_tasks: pacman.yaml
  when: ansible_facts['os_family'] == 'Linux'

- include_tasks: yay.yaml
  when: ansible_facts['os_family'] == 'Linux'
