---
# Pacman Things
- name: Update Pacman cache
  become: true
  pacman:
    update_cache: yes

# Paccache helps to keep only the last 3 versions of packages
- name: Enable paccache timer
  become: true
  systemd:
    name: paccache.timer
    enabled: yes

# Improve Pacman Settings
- name: Update pacman.conf (Part 1)
  become: true
  lineinfile:
    path: "/etc/pacman.conf"
    search_string: "{{item.regex}}"
    line: "{{item.result}}"
  loop:
    - regex: "#Color"
      result: "Color"
    - regex: "#ParallelDownloads = 5"
      result: "ParallelDownloads = 5"

# ILoveCandy gives the Pacman-like progress bars
- name: Update pacman.conf (Part 2)
  become: true
  lineinfile:
    path: "/etc/pacman.conf"
    insertafter: "Color"
    line: "ILoveCandy"

- name: Install reflector
  become: true
  pacman:
    name:
      - reflector

- name: Copy reflector config & pacman hook
  become: true
  copy:
    src: "{{playbook_dir}}/etc/{{item}}"
    dest: "/etc/{{item}}"
    force: no
  loop:
    - xdg/reflector/reflector.conf
    - pacman.d/hooks/mirrorupgrade.hook

# Yay Things
- name: Install base-devel
  become: true
  pacman:
    extra_args: "--needed"
    name:
      - base-devel

- name: Clone yay AUR repo
  when: perform_git_update
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "{{playbook_dir}}/src/yay"
    version: master
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

# Build package without using root, then install yay using root
- name: Build yay
  command:
    cmd: "makepkg -scf --noconfirm"
    chdir: "{{playbook_dir}}/src/yay"
    creates: "{{playbook_dir}}/src/yay/yay-*.tar.gz"

- name: Install yay
  become: true
  pacman: extra_args="-U {{playbook_dir}}/src/yay/yay-*.pkg.tar.zst --needed"

- name: Clone yay ansible module repo
  when: perform_git_update
  git:
    repo: "https://github.com/mnussbaum/ansible-yay.git"
    dest: "{{playbook_dir}}/src/github.com/mnussbaum/ansible-yay"
    version: master
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Create library directory for ansible
  file:
    path: "{{playbook_dir}}/library"
    state: directory

- name: Link yay ansible module
  file:
    src: "{{playbook_dir}}/src/github.com/mnussbaum/ansible-yay/yay"
    dest: "{{playbook_dir}}/library/yay"
    state: link
