---
- name: Update Pacman cache
  become: true
  pacman:
    update_cache: yes

# Paccache helps to keep only the last 3 versions of packages
- name: Enable paccache timer
  become: true
  systemd:
    name: paccache.timer
    enabled: yes

# Improve Pacman Settings
- name: Update pacman.conf (Part 1)
  become: true
  lineinfile:
    path: "/etc/pacman.conf"
    search_string: "{{item.regex}}"
    line: "{{item.result}}"
  loop:
    - regex: "#Color"
      result: "Color"
    - regex: "#ParallelDownloads = 5"
      result: "ParallelDownloads = 5"

# ILoveCandy gives the Pacman-like progress bars
- name: Update pacman.conf (Part 2)
  become: true
  lineinfile:
    path: "/etc/pacman.conf"
    insertafter: "Color"
    line: "ILoveCandy"

- name: Install reflector
  become: true
  pacman:
    name:
      - reflector

- name: Copy reflector config & pacman hook
  become: true
  copy:
    src: "{{playbook_dir}}/etc/{{item}}"
    dest: "/etc/{{item}}"
    force: no
  loop:
    - xdg/reflector/reflector.conf
    - pacman.d/hooks/mirrorupgrade.hook
