---
- name: Install base-devel
  become: true
  pacman:
    extra_args: "--needed"
    name:
      - base-devel

- name: Clone yay AUR repo
  when: perform_git_update
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "{{playbook_dir}}/src/yay"
    version: master
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

# Build package without using root, then install yay using root
- name: Build yay
  command:
    cmd: "makepkg -scf --noconfirm"
    chdir: "{{playbook_dir}}/src/yay"
    creates: "{{playbook_dir}}/src/yay/yay-*.tar.gz"

- name: Install yay
  become: true
  pacman: extra_args="-U {{playbook_dir}}/src/yay/yay-*.pkg.tar.zst --needed"

# Note: The ansible module for yay is installed via `make setup`
