---
- name: Install Flameshot
  become: true
  pacman:
    name:
      - flameshot
      - zbar # Used for parsing QR codes in screenshots

- name: Link config for flameshot
  file:
    src: "{{playbook_dir}}/home/config/flameshot"
    dest: "~/.config/flameshot"
    state: link
