---
- name: Install Bluetooth packages
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - bluez
      - bluez-utils

# TODO: Install via yay
# - bluetooth-headset-battery-level-git

- name: Enable Bluetooth
  become: true
  systemd:
    name: bluetooth
    enabled: yes
