---
- name: Install Bluetooth packages
  become: true
  pacman:
    name:
      - blueman
      - bluez
      - bluez-utils

- name: Install Bluetooth packages - yay
  yay:
    name:
      - bluetooth-headset-battery-level-git

- name: Enable Bluetooth
  become: true
  systemd:
    name: bluetooth
    enabled: yes

- name: Append manual step - Check Bluetooth module is loaded
  set_fact:
    manual_steps: "{{ manual_steps + [ 'Bluetooth - Check that the `btusb` module is loaded. If not, load it' ] }}"
