---
- name: Install Docker packages
  become: true
  pacman:
    name:
      - docker
      - docker-compose

# Enabling the socket allows systemd to delay starting docker until it's needed
- name: Enable Docker
  become: true
  systemd:
    name: docker.socket
    enabled: yes
