---
- name: Install packages to disable Nvidia GPU
  become: true
  pacman:
    name:
      - linux-lts-headers
      - bbswitch-dkms

- name: Copy modprobe config to load & configure bbswitch
  become: true
  copy:
    src: "{{playbook_dir}}/etc/{{item}}"
    dest: "/etc/{{item}}"
    force: no
  loop:
    - modprobe.d/bbswitch.conf
    - modprobe.d/blacklisted.conf
    - modules-load.d/bbswitch.conf
