---
- name: Install IntelliJ
  yay:
    name:
      - intellij-idea-ultimate-edition

- name: Link config for IdeaVim plugin
  file:
    src: "{{playbook_dir}}/home/ideavimrc"
    dest: "~/.ideavimrc"
    state: link
