---
- name: Install NetworkManager
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - networkmanager
      - network-manager-applet

- name: Enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    enabled: yes
