---
- name: Install NetworkManager
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - networkmanager
      - network-manager-applet

- name: Enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    enabled: yes
