---
- name: Create code directory
  file:
    path: "~/code"
    state: directory

# TODO: Figure out what to do when there's local modifications to the script (e.g: credentials)
#- name: Clone internet_usage repo
#  when: perform_git_update
#  git:
#    repo: "git@bitbucket-personal.org:hbotp/internet-usage.git"
#    dest: "~/code/internet-usage"
#    version: master
#  register: git_result
#  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

# TODO: Figure out how to get credentials into the script

- name: Link get_internet_usage script & timer
  become: true
  file:
    src: "{{playbook_dir}}/../code/internet-usage/{{item.file}}"
    dest: "{{item.dest}}/{{item.file}}"
    state: link
  loop:
    - file: "get_internet_usage"
      dest: "/usr/local/bin"
    - file: "get_internet_usage.service"
      dest: "/etc/systemd/system"
    - file: "get_internet_usage.timer"
      dest: "/etc/systemd/system"

- name: Enable get_internet_usage.timer
  become: true
  systemd:
    name: get_internet_usage.timer
    enabled: yes
    state: started
    daemon_reload: yes
