---
- name: Install NetworkManager and helpful packages
  become: true
  pacman:
    name:
      - networkmanager
      - network-manager-applet
      - gnome-keyring

- name: Enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    enabled: yes
