---
- name: Install common fonts
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-anonymous-pro
      - ttf-dejavu
      - ttf-liberation
      # TODO: AUR only
      # - ttf-muli
      # - ttf-symbola

- name: Install CLI utilities
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - bash
      - bash-completion
      - git
      - htop
      - jq
      - keychain
      - sed
      - the_silver_searcher
      - tree
      - unzip
      # TODO: Separate into other roles/tasks
      - arandr
      - autorandr
      - code
      - dnsutils
      - docker
      - docker-compose
      - feh
      - gnu-netcat
      - ipcalc
      - openldap
      - pavucontrol
        #- pulseaudio
      - redshift
      - signal-desktop
      - traceroute
      - vlc
      - yubikey-manager
      - yubikey-manager-qt
      # TODO: Are these needed?
      #- fzf
      #- picom
      #- xscreensaver

# TODO: Install these via yay
# For now, install them manually
#- name: Install some AUR packages
#      - autojump
#      - dmenu2
#      - intellij-idea-ultimate-edition
#      - ngrok
#      - postman-bin
#      - perl-clipboard
#      - slack-desktop
#      - spotify
#      - zoom

- name: Install Python
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - python
      - python2
      - python-pip

- name: Install Python packages
  pip: name="{{item.packages}}" extra_args="--user" state=present
  loop:
    - packages:
      - virtualenv
      - virtualenvwrapper
      - tox

- include: browser.yaml
- include: internet.yaml
- include: yay.yaml
