---
- name: Install common fonts
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - ttf-anonymous-pro
      - ttf-dejavu
      - ttf-liberation
      # TODO: AUR only
      # - ttf-muli
      # - ttf-symbola

- name: Install CLI utilities
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - bash
      - bash-completion
      - git
      - htop
      - jq
      - keychain
      - sed
      - the_silver_searcher
      - tree
      - unzip
      # TODO: Separate into other roles/tasks
      - arandr
      - autorandr
      # TODO: Are these needed?
      #- fzf
      #- picom
      #- xscreensaver

- name: Install Python
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present
  loop:
    - packages:
      - python
      - python2
      - python-pip

- name: Install Python packages
  pip: name="{{item.packages}}" extra_args="--user" state=present
  loop:
    - packages:
      - virtualenv
      - virtualenvwrapper
      - tox

- include: browser.yaml
- include: internet.yaml
