---
- name: Install common fonts
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-anonymous-pro
      - ttf-dejavu
      - ttf-liberation
      # TODO: AUR only
      # - ttf-muli
      # - ttf-symbola

- name: Install CLI utilities
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - bash
      - bash-completion
      - git
      - htop
      - jq
      - keychain
      - sed
      - the_silver_searcher
      - tree
      - unzip
      # TODO: Separate into other roles/tasks
      - alsa-utils
      - arandr
      - autorandr
      - code
      - bind
      - feh
      - gnu-netcat
      - ipcalc
      - openldap
      - pacman-contrib
      - redshift
      - signal-desktop
      - traceroute
      - vlc
      - yubikey-manager
      - yubikey-manager-qt
      # TODO: Is this needed?
      #- fzf

# TODO: Install these via yay
# For now, install them manually
#- name: Install some AUR packages
#      - autojump
#      - dmenu2
#      - intellij-idea-ultimate-edition
#      - ngrok
#      - postman-bin
#      - perl-clipboard
#      - slack-desktop
#      - spotify
#      - zoom

- name: Install Python
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - python
      - python2
      - python-pip
      - python-tox
      - python-virtualenv
      - python-virtualenvwrapper

- include: bluetooth.yaml
- include: browser.yaml
- include: docker.yaml
- include: gpu.yaml
- include: internet.yaml
- include: internet_usage.yaml
- include: sound.yaml
- include: yay.yaml
