---
- name: Install common fonts
  become: true
  pacman:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-anonymous-pro
      - ttf-dejavu
      - ttf-liberation

# TODO: Uncomment if there's some missing Unicode symbols, like emojis
#- name: Install common fonts - yay
#  yay:
#    name:
#      - ttf-symbola

- name: Install CLI utilities
  become: true
  pacman:
    name:
      - bash
      - bash-completion
      - git
      - htop
      - jq
      - keychain
      - sed
      - the_silver_searcher
      - tree
      - unzip
      # TODO: Separate into other roles/tasks
      - alsa-utils
      - arandr
      - autorandr
      - code
      - bind
      - feh
      - gnu-netcat
      - ipcalc
      - openldap
      - pacman-contrib
      - redshift
      - signal-desktop
      - traceroute
      - vlc
      - yubikey-manager
      - yubikey-manager-qt
      # TODO: Is this needed?
      #- fzf

- name: Install some AUR packages - yay
  yay:
    name:
      - autojump
      - dmenu2
      - intellij-idea-ultimate-edition
      - ngrok
      - postman-bin
      - perl-clipboard
      - slack-desktop
      - spotify
      - zoom

- name: Install Python
  become: true
  pacman:
    name:
      - python
      - python2
      - python-pip
      - python-tox
      - python-virtualenv
      - python-virtualenvwrapper

- include: backlight.yaml
- include: bluetooth.yaml
- include: browser.yaml
- include: docker.yaml
- include: gpu.yaml
- include: internet.yaml
- include: internet_usage.yaml
- include: kernel-modules-hook.yaml
- include: sound.yaml
- include: ssd.yaml
- include: udev.yaml
