---
- name: Install Sound packages
  become: true
  pacman: name="{{packages}}" update_cache=yes
  vars:
    packages:
      - pavucontrol
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pulseaudio-alsa
