---
- name: Enable SSD Trim timer
  become: true
  systemd:
    name: fstrim.timer
    enabled: yes

- debug:
    msg:
      - "Manual step:"
      - "SSD Trim - Add `:allow-discards` and `rd.luks.options=discard` to Grub config: https://wiki.archlinux.org/title/Dm-crypt/Specialties#Discard/TRIM_support_for_solid_state_drives_(SSD)"
