---
- name: Install base-devel
  become: true
  pacman: name="{{packages}}" update_cache=yes extra_args="--needed"
  vars:
    packages:
      - base-devel

- name: Clone yay AUR repo
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "{{playbook_dir}}/src/yay"
    version: master

# Build package without using root, then install yay using root
- name: Build yay
  command:
    cmd: "makepkg -scf --noconfirm"
    chdir: "{{playbook_dir}}/src/yay"
    creates: "{{playbook_dir}}/src/yay/yay-*.tar.gz"

- name: Install yay
  become: true
  pacman: extra_args="-U {{playbook_dir}}/src/yay/yay-*.pkg.tar.zst --needed"
