---
- name: Install base-devel
  become: true
  pacman: name="{{item.packages}}" update_cache=yes state=present extra_args="--needed"
  loop:
    - packages:
      - base-devel

- name: Clone yay AUR repo
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "{{playbook_dir}}/src/yay"
    version: master

# Build package without using root, then install yay using root
- name: Build yay
  command:
    cmd: "makepkg -scf --noconfirm"
    chdir: "{{playbook_dir}}/src/yay"

- name: Install yay
  become: true
  pacman: update_cache=yes state=present extra_args="-U {{playbook_dir}}/src/yay/yay-*.tar.gz"
