#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# Grub Entry for Shutdown
menuentry "System shutdown" {
	echo "System shutting down..."
	halt
}

# Grub entry for Reboot
menuentry "System reboot" {
	echo "System rebooting..."
	reboot
}
