---
- name: Clone yay ansible module repo
  git:
    repo: "https://github.com/mnussbaum/ansible-yay.git"
    dest: "{{playbook_dir}}/src/github.com/mnussbaum/ansible-yay"
    version: master
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Create library directory for ansible
  file:
    path: "{{playbook_dir}}/library"
    state: directory

- name: Link yay ansible module
  file:
    src: "{{playbook_dir}}/src/github.com/mnussbaum/ansible-yay/yay"
    dest: "{{playbook_dir}}/library/yay"
    state: link

