---
- name: Initialise list of manual steps
  set_fact:
    manual_steps: []

# !all & !min will skip gathering all the other facts, to make it faster
- name: Gather OS facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - 'os_family'

- name: Set some short helpful OS facts
  set_fact:
    mac_os: "{{ ansible_facts['os_family'] == 'Darwin' }}"
    linux: "{{ ansible_facts['os_family'] == 'Linux' }}"

# Saving some time by only updating git repos if it's been a while

- name: Get current day
  shell: "expr $(date +%s) / 86400"
  changed_when: false
  register: today

- name: Get date of previous git repo pull
  shell: "cat timestamp.txt || echo 0"
  changed_when: false
  register: previous_git_pull

- name: Determine if git repos should get updated
  set_fact:
    perform_git_update: "{{ ((today.stdout | int) - (previous_git_pull.stdout | int)) > 30 }}"
